### ISSUE TITLE
Fourier Transform Program Not working with Sound Files

### ISSUE THREAD

**Issue by Titanslayer1104** [mdubey96/noiseColor#3]
Traceback (most recent call last):
  File "fourier.py", line 66, in <module>
    (sig, rate) = librosa.load(file, sr=None)
  File "/home/titanslayer/enter/lib/python3.8/site-packages/librosa/core/audio.py", line 172, in load
    y = to_mono(y)
  File "/home/titanslayer/enter/lib/python3.8/site-packages/librosa/core/audio.py", line 454, in to_mono
    util.valid_audio(y, mono=False)
  File "/home/titanslayer/enter/lib/python3.8/site-packages/librosa/util/utils.py", line 310, in valid_audio
    raise ParameterError("Audio buffer is not finite everywhere")
librosa.util.exceptions.ParameterError: Audio buffer is not finite everywhere

**Comment by mldubey** [comment]
This looks like an issue with the audio file you are using.
Try another one and see if it works.
